### ISSUE TITLE
App crashed when biometrics is not available

### ISSUE THREAD

**Issue by aylarsahebi** [priezz/flutter_local_auth_invisible#17]
hello , thanks for this package
when my phone support biometrics but there is not any biometrics available , and I try to start authenticate with the  _authenticate method , app crashed and does not show "go to setting" dialog as same as official package

D/AuthenticationHelper(21173): Start authentication
E/MethodChannel#plugins.flutter.io/local_auth(21173): Failed to handle method call
E/MethodChannel#plugins.flutter.io/local_auth(21173): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at io.flutter.plugins.localauth.AuthenticationHelper.authenticate(AuthenticationHelper.java:101)
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at io.flutter.plugins.localauth.LocalAuthPlugin.onMethodCall(LocalAuthPlugin.java:105)
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at android.os.Looper.loop(Looper.java:206)
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at android.app.ActivityThread.main(ActivityThread.java:8587)
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#plugins.flutter.io/local_auth(21173): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/flutter (21173): catch isPlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
I/flutter (21173): 	at io.flutter.plugins.localauth.AuthenticationHelper.authenticate(AuthenticationHelper.java:101)
I/flutter (21173): 	at io.flutter.plugins.localauth.LocalAuthPlugin.onMethodCall(LocalAuthPlugin.java:105)
I/flutter (21173): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter (21173): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter (21173): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
I/flutter (21173): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (21173): 	at android.os.MessageQueue.next(MessageQueue.java:335)
I/flutter (21173): 	at android.os.Looper.loop(Looper.java:206)
I/flutter (21173): 	at android.app.ActivityThread.main(ActivityThread.java:8587)
I/flutter (21173): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter (21173): 	at
D/LocalAuthPlugin(21173): LOCAL AUTH STOPPED
D/AndroidRuntime(21173): Shutting down VM
E/AndroidRuntime(21173): FATAL EXCEPTION: main
E/AndroidRuntime(21173): Process: com.example.fingerprint2, PID: 21173
E/AndroidRuntime(21173): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(21173): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
E/AndroidRuntime(21173): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(21173): 	at io.flutter.plugins.localauth.LocalAuthPlugin.stopIfNotStopped(LocalAuthPlugin.java:48)
E/AndroidRuntime(21173): 	at io.flutter.plugins.localauth.LocalAuthPlugin$1.run(LocalAuthPlugin.java:68)
E/AndroidRuntime(21173): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(21173): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21173): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(21173): 	at android.app.ActivityThread.main(ActivityThread.java:8587)
E/AndroidRuntime(21173): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21173): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(21173): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/Process (21173): Sending signal. PID: 21173 SIG: 9
Lost connection to device.

https://user-images.githubusercontent.com/58422068/131239250-ede70834-e80f-42cc-a564-6e3e63ecc25a.mp4

**Comment by aylarsahebi** [comment]
in official package

https://user-images.githubusercontent.com/58422068/131240762-d1d443e2-b481-4cf5-8f9d-6adfd5f80b2d.mp4

**Comment by priezz** [comment]
Hi @aylarsahebi , you should ask for biometrical authentication only if any method is available (non-empty list returned). I have updated the [example](https://github.com/priezz/flutter_local_auth_invisible/blob/master/example/lib/main.dart).

As for going to the system settings, you can implement this logic on the side of you app if you get the empty list of available methods.

**Comment by aylarsahebi** [comment]
thanks @priezz 
I want to when "useErrorDialogs"  property is true and biometrics in not available , go to setting dialog open automatically  and go to biometrics and security of phone,
do you have any solution for this problem?
![Screenshot 2021-08-29 141249](https://user-images.githubusercontent.com/58422068/131246065-118103f3-5b6b-4d09-8db8-3d98fb1b83b8.png)

**Comment by priezz** [comment]
Solution is easy - just show your own dialog with a proposal to go to settings. This package does not do that (and will never do) as soon as its major purpose is to avoid any kind of standard system dialogs and to give the possibility to create you own UI.
Quick search gave me these two packages - [app_settings](https://pub.dev/packages/app_settings), [system_settings](https://pub.dev/packages/system_settings).

**Comment by aylarsahebi** [comment]
thanks for explain
