### ISSUE TITLE
migrating the plugin to the V2 problem

### ISSUE THREAD

**Issue by kiaxseventh** [priezz/flutter_local_auth_invisible#18]
The plugin `flutter_local_auth_invisible` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter
will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by Mohammad-Ezziedden** [comment]
any update ?

**Comment by priezz** [comment]
I doubt there is a solution. It looks that custom auth dialogs are not supported in the V2. I am not 100% sure though. We still have time before getting the next stable Flutter version, so there still is a hope to find some alternative approach. Any suggestions and PRs are welcome!

**Comment by priezz** [comment]
Migrated in 2.1.0
