### ISSUE TITLE
Plugin does not throw error on failed authentication

### ISSUE THREAD

**Issue by ZatacaSystems** [priezz/flutter_local_auth_invisible#3]
If you fail the biometric authentication, the pluggin does not says that the authentication when wrong and when you try again it says PlatformException(auth_in_progress, Authentication in progress, null)

**Comment by michjm** [comment]
Any news on this issue?
After 5 unsuccessful attempts the finger print input is blocked (but authenticateWithBiometrics does not complete the Future.
Trying authentication again you get the "PlatformException(auth_in_progress, Authentication in progress, null)" exception.

The original local_auth package shows in that case a cancel button and a error message in the authentication dialog.

**Comment by priezz** [comment]
Well, I am not sure what exactly the problem is. We do use this plugin in production with no issues. Here is the example:
```dart
  Future<void> _launchScanner() async {
    try {
      while (_biometricsViewSelected) {
        final didAuthenticate =
            await LocalAuthentication().authenticateWithBiometrics(
          localizedReason: 'Please pass the biometrical authentication',
          stickyAuth: false,
          useErrorDialogs: true,
        );
        if (didAuthenticate) {
          widget.onSuccess();
          break;
        }
      }
    } on PlatformException catch (e) {...}
  }
```

So there is no exception, just the `bool` result when calling `LocalAuthentication().authenticateWithBiometrics()`. To ensure, that the library is in the correct state when you do app restart, do `await LocalAuthentication().stopAuthentication();` before launching the scanner.

**Comment by michjm** [comment]
Hi and thank you for the explanation. I tried your code and ran into the same problem:

-I start the auth sequence,
-I use 5 times a wrong fingerprint (I guess the scanning process is blocked for 30 seconds by Android in that case)
-But: I do not get any result (didAuthenticate) back, so the process is still awaiting and I can not show the users what went wrong
-If this happens too often (I think 2 times in a row) then fingerprint scanning is blocked permanently, but again the LocalAuthentication().authenticateWithBiometrics is not completing...

The local_auth has two more exceptions to handle this case: LockedOut and PermanentlyLockedOut.

But maybe I just don't understand how this biometrics really works...

What happens in your app, when you provide 5 times in a row the wrong fingerprint? Can you the just give the correct one and everything works?

Thanks for all your help and best regards
Michi

**Comment by priezz** [comment]
For us `authenticateWithBiometrics()` always return **true** or **false** (see the example above). Maybe if you share your code, it would be easier to see the issue.

As for more exceptions - PRs are always welcome.

**Comment by aylarsahebi** [comment]
hi , when my authentication is wrong , _authenticate method does not call again and  I receive this error
"LOCAL AUTH STOPPED WITH A FLAG OF false"
I expect authenticate start again

**Comment by priezz** [comment]
> hi , when my authentication is wrong , _authenticate method does not call again and I receive this error
> "LOCAL AUTH STOPPED WITH A FLAG OF false"
> I expect authenticate start again

You app logic is on your side. If you want users to try indefinitely, you should launch the method after a failure  by your own.

**Comment by aylarsahebi** [comment]
hi again @priezz 
thanks for explain
can we have this package without "maxTimeoutMillis = maxTimeoutMillis.clamp(3000, 30000)"
because maybe  a user open app and after 30 second want to use fingerprint
