### ISSUE TITLE
Missing plugin Exception(No implementation found for method getAvailableBiometrics

### ISSUE THREAD

**Issue by Muniru0** [priezz/flutter_local_auth_invisible#5]
I just upgraded to flutter 1.17 and I am now getting this error. I had it once and I solved it by downgrading to flutter 1.12. But now I need some of the features of the new upgrade but it is now breaking for me.?

**Comment by priezz** [comment]
We do use it with 1.17 and it works fine. Do remember to do in your project after you upgrade the SDK:
```
flutter clean
flutter pub get
flutter pub upgrade
```

**Comment by Muniru0** [comment]
> We do use it with 1.17 and it works fine. Do remember to do in your project after you upgrade the SDK:
> 
> ```
> flutter clean
> flutter pub get
> flutter pub upgrade
> ```

I did this but it is still breaking

**Comment by Muniru0** [comment]
I think I have seen my flaw... The issue was from me trying to use the android Pre1.12 build. I really wasted my time on that thing...
