### ISSUE TITLE
Not able to see the dialog of fingerprint while going for the authentication.

### ISSUE THREAD

**Issue by dkp123100** [priezz/flutter_local_auth_invisible#6]
@priezz 
I have used the latest version 0.4.1+2, but when I am going for the authentication then not able to see the dialog. and not able to get the callback when authentication is wrong.

Can you please check this?

**Comment by priezz** [comment]
@dkp123100 , what dialog do you expect to see?

**Comment by abhisheks-active** [comment]
@priezz not able to see suggestion (Scan your fingerprint to authenticate) dialog.

**Comment by priezz** [comment]
This package is to **hide** any dialog to let you create a custom one (look at *invisible* in the title ;) ). If it is not what you need, just use the official package for biometric auth.

**Comment by danish1023** [comment]
Still visible in android 10
