### ISSUE TITLE
Increase package:platform to work with latest Flutter beta version

### ISSUE THREAD

**Issue by nikzen** [priezz/flutter_local_auth_invisible#8]
Hi,

we want to use the latest Beta version of Flutter, but the CI fails with:

`Because every version of flutter_local_auth_invisible depends on platform ^2.0.0 and every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.1, flutter_local_auth_invisible is incompatible with flutter_driver from sdk.`

It would be very nice, if you increase the package:platform to:   `platform: ">=2.0.0 <4.0.0"`

**Comment by priezz** [comment]
Feel free to create a PR :)
25 сент. 2020 г., 17:58 +0200, nikzen <notifications@github.com>, писал:
